apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-volume
  namespace: kube-logging
  labels:
    app: es-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
